# -*- coding: utf-8 -*-
'''
Author : Sharon_Tong
Time   : 2020/4/16 18:40 
'''
class DBParam():
    tab_name_cigrt = 'DBREAD.DIM_CIGRT_ALL'
    col_list_cigrt = ['CIGRT_CODE','BAR_CODE','BAR_CODE_FIXED','PACKG_CODE','PROD_ENTP_CODE','BAR_NAME','BAR_NAME_FIXED','BRAND_CODE', \
                'BRAND_NAME','BRAND_NAME_FIXED','PRICE_TYPE_CODE','PRICE_TYPE_NAME','PRICE_SUB_TYPE_CODE','PRICE_SUB_TYPE_NAME', \
                'PROD_TYPE_CODE','PROD_TYPE_NAME','PAK_FORM_CODE','PAK_FORM_NAME','PAK_MAIN_COLOR','PAK_SECND_COLOR',\
                'PAK_QTY_PIECE','PAK_QTY_SLIP','PAK_QTY_BOX','CIGRT_TOTAL_LENTH','CIGRT_LENTH','FILTER_TIP_LENTH', \
                'CIGRT_LENTH_TYPE','PERMT','PERMT_TYPE', 'CATRM','SMOKE_NICOTN', 'FILNG_DATE','LABEL_OWNR','IMPORT_DOMT_LABEL_CODE', \
                'IMPORT_DOMT_LABEL_NAME', 'FILTER_TIP_TYPE_CODE', 'FILTER_TIP_TYPE_NAME', 'MANG_TYPE_CODE','MANG_TYPE_NAME', \
                'IS_IMPTT_BRAND', 'IS_SPECIFICATION','IS_E_BRAN','IS_CIGA','IS_TOP15','IS_ENCOURAGE','IS_HIGH_TIER_CIGRT',\
                'IS_HIGH_PRICE_CIGRT','IS_LOW_TAR','CIG_IS_LOW','IS_BLAST','IS_LP_CIGRT','PRICE_AREA11','TAR_AREA','ALLOT_PRICE',\
                'WHOLE_PRICE','WHOLE_PRICE_RANGE','RETAIL_PRICE_RANGE','RETL_PRICE','VALID_STTS','BELONG_PROVC_MEET', \
                'IND_CODE','IND_NAME','CIGRT_COAT_CLS','CIGRT_CORE_CLS','CIGRT_WEIGHT','PROC_MODE_CODE','PRICE_GRADE_CODE', \
                'MARKET_TIME','PROD_LIFE_CYCLE','IS_DS','PROVC_CODE_S','LOCAL_UPDATE_TIME']

    tab_name_city = 'DBREAD.DIM_CITY'
    col_list_city = ['PROVC_ROWNUM','CITY_ROWNUM','PROVC_CODE','PROVC_NAME','PROVC_NAME_S','CITY_CODE','CITY_NAME','CITY_NAME_S',\
                     'CITY_15W','CAPITAL_CITY','LATITUDE','LONGITUDE','SHP_SN','MARK_CODE','MARK_NAME','AREA_CODE','AREA_NAME',
                     'CITY_CODE_R','CITY_PSN','CITY_CODE_ERP','CITY_NAME_ERP','LOCAL_UPDATE_TIME']

    tab_name_date = 'DBREAD.DIM_DATE'
    col_list_date = ['YEAR_ID','MONTH_ID','WEEK_ID','DATE_ID','DATE_ID_S','DATE_ID_V','WORKDAY','WEEK_DSCB'\
                     ,'WEEK_ID_ZYXX','WEEK_DSCB_ZYXX','WEEK_DAY']


    tem_tab       = 'DBREAD.TEMP_CITY_FLAG'
    col_list_tem  = ['PROVC_CODE','PROVC_NAME','CITY_CODE','CITY_NAME','FLAG','INDEX_ID']



